from enum import Enum

class AllureTag(str, Enum):
    CHARACTERS = 'CHARACTERS'
    LOCATIONS = 'LOCATIONS'
    EPISODES = 'EPISODES'
    REGRESSION = "REGRESSION"
    NEGATIVE_TEST = "NEGATIVE_TEST"

    GET_ENTITY = "GET ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    VALIDATE_ENTITIES = "VALIDATE_ENTITIES"

